pipeline {

    agent any
    
    stages {
        stage('Build') {
            steps {
                dir ("CEME"){
                     sh 'gradle clean build'
                }
            }
        }
        stage('Delivery') {
            steps {
                 echo 'mock delivery'
            }
        }
        
    }
}