pipeline {

    agent any
    
    stages {
        stage('Build') {
            steps {
                sh 'gradle clean build'
            }
        }
        stage('Delivery') {
            steps {
                echo 'mock delivery'
            }
        }
        
    }
}